
# LuckPermsGUI

# notes for configuring:
# keep your added ranks & tracks in the same order for each section otherwise it will not display as expected
# rank-item & track-item is to be put inside single(or double) quotes


global:
  back-item: 'ARROW'
  background-item: 'BLACK_STAINED_GLASS_PANE'
ranks:
  enabled: true
  require-confirm: true
  # rank-name is the luckperms group name
  rank-name:
    - 'owner'
    - 'admin'
  # rank-prefix is what will display in the GUI
  rank-prefix:
    - '&4Owner'
    - '&cAdmin'
  # rank-item is what item will be displayed for each rank in the GUI
  rank-item:
    - 'DIAMOND'
    - 'DIRT'
tracks:
  enabled: true
  require-confirm: true
  # track-name is set as the name of the track // these are defaults feel free to remove
  track-name:
    - 'staff'
    - 'donatorRanks'
  # track-prefix is what will show up when displayed
  track-prefix:
    - '&9Staff'
    - '&5Donator Ranks'
  # track-item is the item that will be shown in the gui
  track-item:
    - 'NAME_TAG'
    - 'DIAMOND'
  promote-item: 'GREEN_WOOL'
  demote-item: 'RED_WOOL'
permissions:
  enabled: true
  # if the selected user is op the gui will display all permissions as red
  permissions:
    - 'essentials.ban'
    - 'lpgui.reload'
